task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.LabelCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDelete.as_view(), name='delete'),
]

task_manager/statuses/urls.py
from django.urls import path
from task_manager.statuses import views

app_name = 'statuses'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.StatusCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDelete.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.TaskCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDelete.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetail.as_view(), name='detail'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.UserCreate.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdate.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDelete.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('Name'))
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Status(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('Name'))
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models
from task_manager.users.models import CustomUser
# from django.contrib.auth.models import User
from task_manager.statuses.models import Status
from task_manager.labels.models import Label
from django.utils.translation import gettext_lazy as _


class Task(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('Name'))
    description = models.TextField(blank=True, verbose_name=_('Description'))
    author = models.ForeignKey(CustomUser,
                               on_delete=models.PROTECT,
                               related_name='tasks',
                               verbose_name=_('Author'))
    status = models.ForeignKey(Status,
                               on_delete=models.PROTECT,
                               verbose_name=_('Status'))
    executor = models.ForeignKey(CustomUser,
                                 on_delete=models.PROTECT,
                                 blank=True,
                                 null=True,
                                 related_name='tasks_to_do',
                                 verbose_name=_('Executor'))
    labels = models.ManyToManyField(Label,
                                    through='LabelRelationTask',
                                    blank=True,
                                    verbose_name=_('Labels'))
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class LabelRelationTask(models.Model):
    label = models.ForeignKey(Label,
                              on_delete=models.PROTECT,
                              null=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class CustomUser(AbstractUser):

    def get_absolute_url(self):
        return reverse('users:index')

    def __str__(self):
        return self.get_full_name()

task_manager/labels/forms.py
from django.forms import ModelForm
from task_manager.labels.models import Label


class LabelForm(ModelForm):

    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm
from task_manager.statuses.models import Status


class StatusForm(ModelForm):

    class Meta:
        model = Status
        fields = ['name']

task_manager/tasks/forms.py
from django.forms import ModelForm
from task_manager.tasks.models import Task


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from task_manager.users.models import CustomUser


class UserForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name',
                  'username', 'password1', 'password2']

    def clean_username(self):
        if 'username' in self.changed_data:
            return super().clean_username()
        return self.cleaned_data.get("username")

task_manager/labels/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from task_manager.labels.models import Label
from task_manager.labels.forms import LabelForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from task_manager.mixins import CustomLoginRequiredMixin


class IndexView(CustomLoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/index.html'


class LabelCreate(CustomLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Create label'),
        'btn_text': _('Create'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('labels:index')
    success_message = _('Label successfully added!')


class LabelUpdate(CustomLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Edit label'),
        'btn_text': _('Edit'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('labels:index')
    success_message = _('Label successfully updated!')


class LabelDelete(CustomLoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Label
    template_name = 'form.html'
    extra_context = {
        'title': _('Delete label'),
        'btn_text': _('Yes, delete'),
        'btn_class': 'btn-danger'}
    success_url = reverse_lazy('labels:index')
    success_message = _('Label successfully deleted!')
    fail_url = reverse_lazy('labels:index')
    denied_message = _("Label is in use, you cannot delete it!")

    def dispatch(self, context, **response_kwargs):
        label = self.get_object()
        if label.task_set.exists():
            messages.warning(self.request, self.denied_message)
            return HttpResponseRedirect(self.fail_url)
        return super().dispatch(context, **response_kwargs)

task_manager/statuses/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from task_manager.statuses.models import Status
from task_manager.statuses.forms import StatusForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from task_manager.mixins import CustomLoginRequiredMixin


class IndexView(CustomLoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/index.html'


class StatusCreate(CustomLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Create status'),
        'btn_text': _('Create'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status successfully added!')


class StatusUpdate(CustomLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Edit status'),
        'btn_text': _('Edit'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status successfully updated!')


class StatusDelete(CustomLoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Status
    template_name = 'form.html'
    extra_context = {
        'title': _('Delete status'),
        'btn_text': _('Yes, delete'),
        'btn_class': 'btn-danger'}
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status successfully deleted!')
    fail_url = reverse_lazy('statuses:index')
    denied_message = _("Status is in use, you cannot delete it!")

    def dispatch(self, context, **response_kwargs):
        status = self.get_object()
        if status.task_set.exists():
            messages.warning(self.request, self.denied_message)
            return HttpResponseRedirect(self.fail_url)
        return super().dispatch(context, **response_kwargs)

task_manager/tasks/views.py
from django.views.generic import (CreateView,
                                  DeleteView,
                                  UpdateView,
                                  DetailView)
from task_manager.tasks.models import Task
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.filter import TaskFilter
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django_filters.views import FilterView
from django.utils.translation import gettext_lazy as _
from task_manager.mixins import CustomLoginRequiredMixin
from task_manager.tasks.mixins import TaskAuthorMixin


class IndexView(CustomLoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/index.html'
    filterset_class = TaskFilter


class TaskDetail(DetailView):
    model = Task
    template_name = 'tasks/detail.html'


class TaskCreate(CustomLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Create task'),
        'btn_text': _('Create'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('tasks:index')
    success_message = _('Task successfully added!')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdate(CustomLoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Edit task'),
        'btn_text': _('Edit'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('tasks:index')
    success_message = _('Task successfully updated!')


class TaskDelete(CustomLoginRequiredMixin, SuccessMessageMixin,
                 TaskAuthorMixin, DeleteView):
    model = Task
    template_name = 'form.html'
    extra_context = {
        'title': _('Delete task'),
        'btn_text': _('Yes, delete'),
        'btn_class': 'btn-danger'}
    success_url = reverse_lazy('tasks:index')
    success_message = _('Task successfully deleted!')
    fail_url = reverse_lazy('tasks:index')

task_manager/users/views.py
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from task_manager.users.models import CustomUser
from task_manager.users.forms import UserForm
from task_manager.users.mixins import CanSelfManageObject, CanObjectBeDeleted
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from task_manager.mixins import CustomLoginRequiredMixin
from django.utils.translation import gettext_lazy as _


class IndexView(ListView):
    model = CustomUser
    template_name = 'users/index.html'


class UserCreate(SuccessMessageMixin, CreateView):
    model = CustomUser
    form_class = UserForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Registration'),
        'btn_text': _('Sign up'),
        'btn_class': 'btn-primary'}
    success_url = reverse_lazy('login')
    success_message = _('Successfully registered!')


class UserUpdate(SuccessMessageMixin,
                 CustomLoginRequiredMixin,
                 CanSelfManageObject,
                 UpdateView):
    model = CustomUser
    form_class = UserForm
    template_name = 'form.html'
    extra_context = {
        'title': _('Edit user'),
        'btn_text': _('Update'),
        'btn_class': 'btn-primary'}
    success_message = _('Successfully updated!')
    success_url = reverse_lazy('users:index')
    permission_denied_message = _("You cannot edit other users!")


class UserDelete(SuccessMessageMixin,
                 CustomLoginRequiredMixin,
                 CanSelfManageObject,
                 CanObjectBeDeleted,
                 DeleteView):
    model = CustomUser
    template_name = 'form.html'
    extra_context = {
        'title': _('Delete user'),
        'btn_text': _('Yes, delete'),
        'btn_class': 'btn-danger'}
    success_message = _('Successfully deleted!')
    success_url = reverse_lazy('users:index')
    permission_denied_message = _("You cannot delete other users!")

    def dispatch(self, context, **response_kwargs):
        if not self.request.user.is_authenticated:
            return CustomLoginRequiredMixin.handle_no_permission(self)
        if not CanSelfManageObject.test_func(self):
            return CanSelfManageObject.handle_no_permission(self)
        if not CanObjectBeDeleted.test_func(self):
            return CanObjectBeDeleted.handle_no_permission(self)
        return super().dispatch(context, **response_kwargs)

task_manager/views.py
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _


class IndexView(TemplateView):
    template_name = 'index.html'


class Login(SuccessMessageMixin, LoginView):
    template_name = 'login.html'
    success_url = reverse_lazy('index')
    success_message = _('Successfully logged in!')


class Logout(SuccessMessageMixin, LogoutView):
    success_url = reverse_lazy('index')
    success_message = _('Successfully logged out!')

    def dispatch(self, request, *args, **kwargs):
        messages.add_message(request,
                             messages.INFO,
                             _('Successfully logged out!'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load i18n %}
{% get_current_language as lang %}

<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% translate 'Task manager' %}</title>
</head>

<body class="min-vh-100 d-flex flex-column">
    
    <header class="container flex-shrink-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">{% translate 'Task manager' %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:index' %}" class="nav-link">{% translate 'Users' %}</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'statuses:index' %}" class="nav-link">{% translate 'Statuses' %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'labels:index' %}" class="nav-link">{% translate "Labels" %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'tasks:index' %}" class="nav-link">{% translate "Tasks" %}</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="nav-link btn" value="{% translate 'Log out ' %}"/>
                        </form>
                    </li>
                    
                    {% else %}

                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">{% translate "Login" %}</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:create' %}" class="nav-link">{% translate "Registration" %}</a>
                    </li>
                    {% endif %}
                </ul>
        </nav>
    </header>
   
    {% block messages %}
    <div class="container flex-shrink-0">
        <div class="messages" id="messages-list">
        {% if messages %}
            {% for message in messages %}
            <p>
                {% if message.tags %}
                     <div class="alert alert-{{ message.tags }} msg fade show" role="alert">{{ message }}</div>
                {% else %}
                    <div class="alert alert-info msg fade show" role="alert">{{ message }}</div>
                {% endif %}
            </p>
            {% endfor %}
        {% endif %}
        </div>
    </div>
        
    {% endblock %}

    <main class="flex-grow-1 container">
    {% block main %}
    {% endblock %}
    </main>
    
    <footer class="container flex-shrink-0 border-top py-3 mt-5">
        <div class="container-lg text-center">
            <a href="https://ru.hexlet.io/" target="_blank">Hexlet</a>
        </div>
    </footer>
</body>
</html>

task_manager/templates/form.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block main %}
<h2 class="mt-3">{{ title }}</h2>

<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn {{ btn_class }}" type="submit" value="{{ btn_text }}">
</form>

{% endblock %}

task_manager/templates/index.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block main %}
<div class="container-lg mt-3">
    <div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 p-5 bg-light">
      <h1 class="display-3">{% translate "Hello from Hexlet!" %}</h1>
        <p class="lead">{% translate "Online School of Programming" %}</p>

        <hr>

        <a href="https://ru.hexlet.io/" class="btn btn-primary btn-lg" target="_blank">{% translate "Learn more" %}</a>

    </div>
    </div>
</div>
{% endblock %}

task_manager/templates/login.html
{% extends "base.html" %}

{% load django_bootstrap5 %}
{% load i18n %}

{% block main %}
<h2 class="mt-3">{% translate "Login" %}</h2>
{% if errors %}
{% endif %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Sign in' %}" class="btn btn-primary" >
</form>
{% endblock %}